nlweb-backend:
  # NeoLoad Web Backend:
  # - 8080: NeoLoad GUI REST Port
  # - 8081: Public API Swagger Port
  # - 9092: NeoLoad Web BackendEnd Monitoring
  ports:
  - 8080:1081
  - 8081:1082
  - 9082:9092
  image: neotys/nlweb-backend-onpremise:latest
  environment:
    MEMORY_MAX: 1300m
    MONGODB_HOST: mongodb-host-name
    MONGODB_PORT: 27017
    MONGODB_MAX_POOLSIZE: 50
  tty: true
  stdin_open: true
  container_name: nlweb-backend
nlweb-frontend:
  # NeoLoad Web Frontend:
  # - 80: NeoLoad Web Interface
  # - 81: NeoLoad Web FrontEnd Monitoring
  ports:
  - 80:9090
  - 81:9091
  image: neotys/nlweb-front-onpremise:latest
  environment:
    MEMORY_MAX: 896m
  links:
  - nlweb-backend
  tty: true
  stdin_open: true
  container_name: nlweb-frontend
