nlweb-backend:
  # NeoLoad Web Backend:
  # - 8080: NeoLoad GUI REST Port
  # - 8081: Public API Swagger Port
  # - 9092: NeoLoad Web BackendEnd Monitoring
  image: neotys/nlweb-backend-onpremise:latest
  environment:
    MEMORY_MAX: 1300m
    MONGODB_HOST: mongodb-host-name
    MONGODB_PORT: 27017
    MONGODB_MAX_POOLSIZE: 50
  tty: true
  stdin_open: true
  container_name: nlweb-backend
nlweb-frontend:
  # NeoLoad Web Frontend:
  # - 80: NeoLoad Web Interface
  # - 81: NeoLoad Web FrontEnd Monitoring
  image: neotys/nlweb-front-onpremise:latest
  environment:
    MEMORY_MAX: 896m
  links:
  - nlweb-backend
  tty: true
  stdin_open: true
  container_name: nlweb-frontend
nginx:
  image: nginx:alpine
  ports:
  - 443:443
  - 444:444
  - 8080:8080
  - 8081:8081
  - 9092:9092
  environment:
  - NGINX_HOST=foobar.com
  volumes:
  - /path/to/your/certs/folder:/cert
  - ./:/etc/nginx/conf.d/
  links:
  - nlweb-frontend
  - nlweb-backend
  container_name: nginx
